### ISSUE TITLE
imap...?

### ISSUE THREAD

**Issue by piwats** [HelloLily/hellolily#18]
Hello folks ;)

I saw Bob's presentation on why you have moved to the Gmail API.

If imap is so problematic, have you thought about rerouting the email in a way you can process it with HelloLilly? After all, imap is just an email storage.

For example, take postfix (exim should do it, too) and let it reroute emails to where ever you need it to be, be it over lmtp or something else? The same happens, f.e. when you run your own mailinglist server like mailman (which plugs in via lmtp, or mlmmj via a special command, mlmmj-receive).

That works, of course, only if you run your own smtp servers and hence have the access.

(Because of information privacy issues and stricter requirements on sensitive information treatment, the use of services provided by google and similar cannot be regarded.)

**Comment by bobvoorneveld** [comment]
Hi piwats,

I'm so sorry for the late response to your issue. Here is our answer:

We really wanted a 2 way sync, so that you can use our platform side by side with your favorite mail program, your phone, etc. We didn't want to host an smtp server and let the user reroute everything. This would make us responsible for their complete email service and that's not something we want to be responsible for.

We actually tried SMTP/IMAP for a while to create a 2 way sync, but the protocol is outdated, doesn't meet the requirements for a nice sync in our opinion and was slow in the way we implemented it. We could probably have done a lot better, but then Gmail api came along. And that api is a lot easier to implement. It keeps track of the changes of an mailaccount, we do not need the username & password anymore of a user, the user can revoke access from within their Google account.

So we're bound to the gmail api for the moment, we are looking for a solution to use non gmail accounts. A this moment, we a couple of companies who use Lily as alpha users and they have their email already in Gmail. I think we will look into this as soon as we have some client who do not want to migrate to gmail for their email and find another solution. But I think we're gonna use something 3rd party to give us an api and let Lily work with the emails in a similar way as with the Gmail api.

One of the reasons it took a little bit longer was that Google revoked almost every token we had for the mailaccounts and we had nothing in place to restore from that. We still don't know why the tokens were revoked, but we do have some system in place to recover from that. So as you can see, we are still learning from email and the api, so we hope we can do better every commit we make.

Thanks for your interest in Lily, we really like the fact that someone is taking an interest in our code.

**Comment by piwats** [comment]
Hello Bob,

thank you very much for your detailed response.

I am looking for a CRM, that is lightweight, looks nice and clean and shiny, is fully open-source (GPL3 is definitely a yay!-factor here), written in python (easier to develop and integrate, f.e. in tryton), can communicate via email.

HelloLily meets that all, except, to some extent, the email communication.

Your aim of having the ability to use all of the user's 'email-access-points' at the same time without creating any duplicity or rerouting is, in comparison with other CRMs, one can say, innovative.

In 2014 Dovecot announced a REST API, that is fully compatible with the Gmail API, that should become open source, too. This could be an alternative. Unfortunately, there is no release of it, as of today, yet. (I've just emailed them to ask about the state of development.)

Not to sound paranoid, privacy is a very big concern. Having sensitive communication data going through Google is from some point of perspective controversial.

Another problem arises from the standpoint of views of different privacy laws: take the German privacy laws for example:

Without a consent I am not allowed to transfer any personally identifiable information to any third party. Transferring data across the ocean, even if such a possibility exists, is at the moment, after the latest EU court rulings, very problematic. In Germany, after some rulings, I am not allowed to transfer any data to the US, as a treatment of data to the accordance with the German privacy laws cannot be guaranteed. It is impossible now to get an allowance from the authorities on the transfer of data to the US, as one cannot rule out that Google won't store this specific data in the US.

How the situation looks like in other European countries after the Safe-Harbour agreement was ditched by the European Court of Justice, I do not know, but rulings may be similar.

These are some very nasty implications.

Still, I am very interested (as part of an start up, we are interested as well) in HelloLily.

Staying tuned on the development of HelloLily :)

**Comment by bobvoorneveld** [comment]
Great to read that your interested!
I'm not a legal expert in the matter of privacy, so I'm not capable of given a good answer to that question. We are keeping track of several initiatives that implement some sort of api that works together with imap, we'll add Dovecot to the list.
If you want to extend anything to Lily, let us know if you need help in any way. We love to hear what you guys add to the platform or make use of.

**Comment by piwats** [comment]
Hello Bob,
Hello HelloLily team,

there are some news regarding this topic:

http://comments.gmane.org/gmane.mail.imap.dovecot/85277

> ...we are also going to provide http://jmap.io based HTTP API for accessing
emails in future community release. 
> 
> Aki Tuomi
> Dovecot Oy

:-)
